### ISSUE TITLE
Zeebe Resource Deployer not using the host logger

### ISSUE THREAD

**Issue by ArchieHill** [camunda-community-hub/zeebe-client-csharp-accelerator#3]
**Describe the bug**

The Zeebe Resource Deployer does not use the same logger as the rest of the code as observed here:
![Github](https://github.com/camunda-community-hub/zeebe-client-csharp-accelerator/assets/94839295/09e22627-9edd-4198-bffb-0ec83c937b25)

I believe this is because its using its own create logger instead of inputting the default one through the constructor

**To Reproduce**

1. Replace the default logger with a different logger like Serilog
2. Run a deployment of resources with other logs
3. Observe different formatting of logs

**Expected behavior**

The logs for resource deployer follow the same format as the rest of the logging

**Enviroment (please complete the following information):**

 - OS: Windows
 - Version 1.0.2

**Additional context**

**Comment by VonDerBeck** [comment]
@ArchieHill:
Good catch. Thanks! 👍 
This should be fixed in the new version 1.0.3. If you still have problems please reopen the ticket or open a new one.
