### ISSUE TITLE
I would like to provide the zb-client-sharp my custom AccessTokenSupplier

### ISSUE THREAD

**Issue by taneltinits** [camunda-community-hub/zeebe-client-csharp-accelerator#32]
### Problem

Right now the zb-client-sharp AccessTokenSupplier is quite simple http client that fetches tokens and caches it to file. With high load and multithreaded usage its not performing well and is causing file locks and due to that errors in logs.

### Solution

With zb-client-sharp there is possibility to provide custom token supplier in the client builder. The builder has to implement IAccessTokenSupplier interface which is included in the zb-client-sharp.

Idea is in the accelerator setup to check if there is a service implementing IAccessTokenSupplier registered in DI and if its there, it will be provided to the zb-client builder. 
Possible fix is done in the PR: https://github.com/camunda-community-hub/zeebe-client-csharp-accelerator/pull/31

**Describe alternatives you've considered**

Alternate solution would be to update zb-client-sharp token supplier code - it would need more advanced token provider. But as there are already decent libraries that have those so no reason to build it in there. (ie [Duende.AccessTokenManagement](https://github.com/DuendeSoftware/Duende.AccessTokenManagement)

**Additional context**

Explanation how to use custom provider is also under the zb-client-sharp discussions: https://github.com/camunda-community-hub/zeebe-client-csharp/discussions/666

**Comment by VonDerBeck** [comment]
@taneltinits:
Thanks again for your input. I just released version 2.1.8 including your suggested enhancement. 👍
