### ISSUE TITLE
Unable to use abstract classes

### ISSUE THREAD

**Issue by jprubio** [camunda-community-hub/zeebe-client-csharp-accelerator#4]
Hi everyone,

I'm trying to use abstract class on top on all my IAsyncZeebeWorkers classes (derivative classes). I faced that BootstrapZeebe scan in assemblies and try to register using DeclaringType instead of ReflectedType.

If ReflectedType is used in AddZeebeJobHandlers method (ServiceCollectionExtensions) and in HandleJob (ZeebeJobHandler.cs) all goes fine.

Thanks.

**Comment by VonDerBeck** [comment]
Hi @jprubio,

good catch 👍 - thanks. I will have a look at this.

**Comment by jprubio** [comment]
Good job!
