### ISSUE TITLE
ZeebeClient in the example application can send the command successfully for only once

### ISSUE THREAD

**Issue by send2vinnie** [camunda-community-hub/zeebe-client-csharp-accelerator#7]
**Describe the bug**

The command NewCreateProcessInstanceCommand() only gets sent to the local Zeebe docker via ZeebeClient successfully for once after the example web application is up and running and then it goes down for the subsequent requests without any errors.

**To Reproduce**

1. Spin up the example web application
2. Go to the Swagger UI provided by the example
3. Submit an application
4. Check the process instance in Operator. A new instance is created.
5. Go to Swagger UI and submit another application
6. Check the process instance in Operator. The number of the instance remains the same.

**Expected behavior**

A new process instance should be created whenever a new application is submitted via ZeebeClient.

**Enviroment (please complete the following information):**

 - OS: Windows
 - Version: 11
 - Zeebe: 8.2.11 (running in Docker Desktop)

**Comment by VonDerBeck** [comment]
@send2vinnie:
Thank you for pointing this out. This is an error caused by the underlying zb-client and their migration to the Grpc.net.GrpcChannel away from Grpc.core.

As a workaround I would suggest to go back to version 1.1.0 of this library which has zb-client 1.3.0 as transitive dependency.

**Comment by VonDerBeck** [comment]
This missing async has been added to the Controller and documentation been updated. Thanks for your hint!
