### ISSUE TITLE
I can use the client to subscribe to a task without completing it

### ISSUE THREAD

**Issue by chDame** [camunda-community-hub/zeebe-client-csharp-accelerator#8]
Problem : I want to subscribe to usertasks to push them through websockets to the front-end without waiting for tasklist to be populated. I'd like a worker without autocomplete

Solution : A worker that is Void and not completing the job.

Alternative : sending an exception... but that's ugly :)

Thanks in advance for any feedback (perhaps I missed something)

**Comment by VonDerBeck** [comment]
@chDame: thanks for bringing this up. I agree that there should be a way to use workers without autocompletion but leave this to the user. I will have a look into it. 👍

**Comment by VonDerBeck** [comment]
@chDame: A solution with support for a new attribute `[AutoComplete(false)]` will be released within the next days.

**Comment by VonDerBeck** [comment]
@chDame: I just published version 2.1.2. Thanks again for your input.

**Comment by chDame** [comment]
Hi Gunnar, many thanks ! It's highly appreciated! I'll soon use it :)
