### ISSUE TITLE
Upgrade to use ZbClient 2.2 to target both net6 and net7

### ISSUE THREAD

**Issue by hatzhang** [camunda-community-hub/zeebe-client-csharp-accelerator#9]
Since ZbClient 2.2 now is multiple targeted, maybe we should upgrade to 2.2, so this can also support net6 and net7.

**Comment by VonDerBeck** [comment]
@hatzhang: thanks. I have indeed overlooked the version 2.2. An update makes sense of course.

**Comment by VonDerBeck** [comment]
I just published version 2.1.2. Thanks again for your input.
